#!/bin/sh

# This installation is destructive, as it removes exisitng files/directories.
# Use at your own risk.

for name in *; do
  if [ ! $name == "README.rdoc" -a ! $name == "LICENSE" -a ! $name == "install" -a ! $name == "update_bundles" ]; then

    target="$HOME/.$name"

    if [ -h $target ]; then
      rm $target
      echo "Deleted $target."
    elif [ -d $target ]; then
      rm -rf $target
      echo "Deleted $target."
    fi

    ln -s "$PWD/$name" "$target"
    echo "Linked $PWD/$name to $target."
  fi
done

# install vundle
echo "Installing vundle..."
git clone http://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
echo "done"

echo
echo "Don't forget to run :BundleInstall"
echo