#!/bin/sh

# This installation is destructive, as it removes exisitng files/directories.
# Use at your own risk.

# install vundle
echo "Installing vundle..."
  if [ -d "vim/bundle/vundle" ]; then
    cd "vim/bundle/vundle"
    git pull
    cd "../../.."
  else
    git clone http://github.com/gmarik/vundle.git vim/bundle/vundle
  fi
echo "Done installing vundle."

# Symlink all of the files in the repo to your home directory.
for name in *; do
  if [ ! $name == "README.md" -a ! $name == "LICENSE" -a ! $name == "install" ]; then
    target="$HOME/.$name"

    if [ -h $target ]; then
      rm $target
      echo "Deleted $target"
    elif [ -d $target ]; then
      rm -rf $target
      echo "Deleted $target"
    fi

    ln -s "$PWD/$name" "$target"
    echo "Linked $PWD/$name to $target."
  fi
done

vim -c BundleInstall! -c BundleClean! -c q -c q

# Install jsctags for taglist
# Using this fork since it works with npm
npm install -g https://github.com/Swatinem/doctorjs/tarball/master

gem install CoffeeTags

# cd vim/bundle/Command-T
# For some reason rvm is not a function here...
# [[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" && rvm system
# rake make
# [[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" && rvm default

echo
echo "Installed successfully."
echo

