#!/usr/bin/env ruby

# Variations:
# https://gist.github.com/593551/5b174cd1dd5037954992788c451683a92d9ef79a
# https://gist.github.com/570398
# https://gist.github.com/414542

git_bundles = [ 
  "git://github.com/mileszs/ack.vim.git",
  "git://github.com/tsaleh/vim-align.git",
  "git://github.com/msanders/cocoa.vim.git",
  "git://github.com/kchmck/vim-coffee-script.git",
  # "git://git.wincent.com/command-t.git",
  "git://github.com/tpope/vim-cucumber.git",
  "git://github.com/jayferd/eco.vim.git",
  "git://github.com/geetarista/ego.vim.git",
  "git://github.com/tpope/vim-endwise.git",
  "git://github.com/tpope/vim-fugitive.git",
  "git://github.com/mattn/gist-vim.git",
  "git://github.com/sjl/gundo.vim.git",
  "git://github.com/tpope/vim-haml.git",
  "git://github.com/nelstrom/vim-mac-classic-theme.git",
  "git://github.com/tpope/vim-markdown.git",
  "git://github.com/robgleeson/vim-markdown-preview.git",
  "git://github.com/mhz/vim-matchit.git",
  "git://github.com/scrooloose/nerdcommenter.git",
  "git://github.com/tpope/vim-pastie.git",
  "git://github.com/tpope/vim-ragtag.git",
  "git://github.com/tpope/vim-rake.git",
  "git://github.com/tpope/vim-rails.git",
  "git://github.com/tpope/vim-repeat.git",
  "git://github.com/vim-scripts/RltvNmbr.vim.git",
  "git://github.com/taq/vim-rspec.git",
  "git://github.com/vim-ruby/vim-ruby.git",
  "git://github.com/astashov/vim-ruby-debugger.git",
  "git://github.com/cakebaker/scss-syntax.vim.git",
  "git://github.com/tsaleh/vim-shoulda.git",
  "git://github.com/harleypig/ShowMarks.git",
  "git://github.com/msanders/snipmate.vim.git",
  "git://github.com/scrooloose/snipmate-snippets.git",
  "git://github.com/bingaman/vim-sparkup.git",
  "git://github.com/vim-scripts/Specky.git",
  # "git://github.com/tsaleh/vim-supertab.git",
  # "git://github.com/tsaleh/vim-tcomment.git",
  "git://github.com/tpope/vim-surround.git",
  "git://github.com/scrooloose/syntastic.git",
  "git://github.com/mexpolk/vim-taglist.git",
  "git://github.com/tpope/vim-unimpaired.git",
  "git://github.com/canadaduane/VimKata.git",
  "git://github.com/vim-scripts/VisIncr.git",
  "git://github.com/chrismetcalf/vim-yankring.git"
]

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "vim/bundle")

FileUtils.cd(bundles_dir)

puts "Trashing everything (lookout!)"
Dir["*"].each {|d| FileUtils.rm_rf d }

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  puts "  Unpacking #{url} into #{dir}"
  `git clone #{url} #{dir}`
  FileUtils.rm_rf(File.join(dir, ".git"))
end
